@echo off
echo Starting Vite dev server...
start "Vite Dev Server" cmd /k "npm run dev"
echo Waiting 4 seconds for Vite to start...
timeout /t 4 /nobreak > nul
echo Starting Electron...
start "Electron" cmd /k "npm run electron:dev"
